### ISSUE TITLE
Enhancement - API code generated from POSTMAN/Swagger descriptor

### ISSUE THREAD

**Issue by app-generator** [app-generator/api-server-laravel#8]
**Follow UP** Thread
---

In the long run, the API should be provisioned automatically based on an input file. 
Ideally, the automatized process should follow this setup:

- Input File: POSTMAN or Swagger
- API code automatically generated 
  - new methods should preserve the header constraints 
- Database tables

**Comment by rennokki** [comment]
~@app-generator Can you pass the Postman/Swagger example files I can work with?~ I have it.

**Comment by app-generator** [comment]
Fixed in v1.0.0.
Ty @rennokki 

Closing.
