### ISSUE TITLE
Login Error - Cannot Authenticate User

### ISSUE THREAD

**Issue by app-generator** [app-generator/api-server-laravel#9]
## Context

- Registration ok
- Login -> Not ok 
- Environment: 
  - OS: Ubuntu 18.04
  - PHP 7.4.3 
  - Composer 2.1.6

## How to reproduce 

- Fresh install via GIT
- Execute the README set up
- Send registration request -> OK

```json
{
    "username":"test",
    "password":"pass", 
    "email":"test@appseed.us"
}
``` 

- Try to authenticate -> NOT OK
  - Request 
```json
{
    "password":"pass", 
    "email":"test@appseed.us"
}
```
  - Response
```json
{
    "success": false,
    "msg": "Wrong credentials."
}
```

--- 
Nothing relevant in runtime logs.

**Comment by rennokki** [comment]
@app-generator Got the original Postman implementation when testing it? I can't seem to be able to replicate it through tests.

**Comment by app-generator** [comment]
Hello @rennokki,

The POSTMAN descriptor is saved in the root of the project:

https://github.com/app-generator/api-server-laravel/blob/main/api-server-generic.postman_collection
